# Generated by Django 2.1.5 on 2019-03-31 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_auto_20190216_2306'),
        ('qanswers', '0004_merge_20190320_0416'),
        ('users', '0008_auto_20190320_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='notification', max_length=200)),
                ('isBook', models.IntegerField(default=1)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qanswers.Question')),
            ],
        ),
    ]
