# Generated by Django 2.1.5 on 2019-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190216_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
    ]
