# Generated by Django 2.1.5 on 2019-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20190220_0154'),
        ('users', '0002_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='following', to='authors.Author'),
        ),
    ]
