# Generated by Django 2.1.5 on 2019-03-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_following'),
        ('users', '0002_auto_20190319_2345'),
    ]

    operations = [
    ]
