# Generated by Django 2.1.5 on 2019-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20190320_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='../user_avatar/IMG_8613.jpg', null=True, upload_to='user_avatar'),
        ),
    ]
