# Generated by Django 2.1.5 on 2019-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190320_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user_avatar/IMG_8613.jpg', null=True, upload_to='user_avatar'),
        ),
    ]
