# Generated by Django 2.1.5 on 2019-03-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190320_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/user_avatar/logo.jpg', null=True, upload_to='user_avatar'),
        ),
    ]
