# Generated by Django 2.1.5 on 2019-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190320_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
