# Generated by Django 2.0 on 2019-04-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190320_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
