# Generated by Django 2.1.5 on 2019-04-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_authorreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorreview',
            name='prof',
        ),
        migrations.DeleteModel(
            name='AuthorReview',
        ),
    ]
