# Generated by Django 2.1.5 on 2019-03-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanswers', '0003_auto_20190319_2345'),
        ('qanswers', '0003_auto_20190315_2010'),
    ]

    operations = [
    ]
